### ISSUE TITLE
Change SSL certificates

### ISSUE THREAD

**Issue by dmolina-ot** [NREL/api-umbrella#112]
How can I change default self signed certificates by my own certificates? Is there some attribute in api-umbrella.yml to do this?

**Comment by GUI** [comment]
This is untested (we currently perform SSL termination outside API Umbrella), but I believe this should be possible with this config in your `/etc/api-umbrella/api-umbrella.yml`file:

```
hosts:
  - hostname: your_hostname.com
    default: true
    ssl_cert: /your/path/to/ssl.crt
    ssl_cert_key: /your/path/to/ssl.key
```

You can store the cert files wherever you'd like on your server.

These paths get passed to the `[ssl_certificate](http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_certificate)` and `[ssl_certificate_key](http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_certificate_key)` settings for nginx. If you haven't installed SSL certs into nginx before, then I think the main thing to be aware of is that the certificate file needs to contain any intermediate certs inside the file directly (there's not a separate intermediate configuration setting like with Apache's SSL config).

Let me know if that doesn't do the trick, though.
