### ISSUE TITLE
Call URL for github oauth

### ISSUE THREAD

**Issue by ThibautGery** [NREL/api-umbrella#233]
I use the following configuration, I couldn't find the callback URL for Github. Can you point me to the part of the documentation where it is explained ?

Thank you

```
web:
  admin:
    initial_superusers:
      - someone@api.gouv.fr
    auth_strategies:
      enabled:
        - github
        - persona
      github:
        client_id: <redacted>
        client_secret: <redacted>
```
