### ISSUE TITLE
Disable Eslasticsearch

### ISSUE THREAD

**Issue by rogeriollacerda** [NREL/api-umbrella#262]
Can I disable elasticsearch resouce on Umbrella? We already use an external.

**Comment by GUI** [comment]
Yes, this is possible. See the [Multi-Server Setup](https://api-umbrella.readthedocs.io/en/latest/server/multi-server.html) part of the documentation about how to configure this. Basically, you'll update `/etc/api-umbrella/api-umbrella.yml` with something like:

```yml
services:
  - general_db
  # log_db should *not* be enabled if you want to rely on an external Elasticsearch cluster.
  # - log_db
  - router
  - web
elasticsearch:
  hosts:
    - http://your-elasticsearch-server1.example.com:9200
    - http://your-elasticsearch-server2.example.com:9200
    - http://your-elasticsearch-server3.example.com:9200
```

If you're external Elasticsearch instance is version 2 or greater, than you'll also want to look at [External Database Usage](https://api-umbrella.readthedocs.io/en/latest/server/db-config.html#external-database-usage) (you'll need to add an extra config setting for Elasticsearch 2 compatibility).
