### ISSUE TITLE
Unable to access homepage

### ISSUE THREAD

**Issue by sharmaashish** [NREL/api-umbrella#263]
I followed the instructions on the Getting Started page and installed it via yum on Centos 7.
Tried starting it using both init.d and systemctl 
However when I start and browse to `http://<my hostname>:80/` or `http://localhost:80/` I get nothing.
Confirmed that port 80 is open (actually, I just turned off the firewall)
Also no services seem to be running on port 80 `netstat -lnput|grep :80` gives a blank.
`/etc/api-umbrella/api-umbrella.yml` looks like:

``` yml
services:
#   - general_db
#   - log_db
#   - router
   - web
web:
  admin:
    initial_superusers:
      - ashish.sharma@emory.edu
#     auth_strategies:
#       enabled:
#         - github
#         - google
#         - persona
#       github:
#         client_id:
#         client_secret:
#       google:
#         client_id:
#         client_secret:
# elasticsearch:
#   hosts:
#     - http://127.0.0.1:14002
mongodb:
  url: mongodb://127.0.0.1:27017/api_umbrella
# nginx:
#   workers: 4
# gatekeeper:
#   workers: 4
```
