### ISSUE TITLE
Sub-URL Request settings have no effect

### ISSUE THREAD

**Issue by c1784497** [NREL/api-umbrella#359]
After installing i have setup an API backend:

```
backend_host: test.redacted.ext
backend_protocol: http
balance_algorithm: least_conn
frontend_host: apiumbrella.redacted.ext
name: swaggerpetstore
servers:
- host: test.redacted.ext
  port: 80
settings:
  api_key_verification_level: 
  disable_api_key: 
  error_data: {}
  error_templates: {}
  rate_limit_mode: 
  require_https: optional
  required_roles:
  - user
sort_order: 0
sub_settings:
- http_method: POST
  regex: "^/pet/*"
  settings:
    api_key_verification_level: required_email
    error_data: {}
    error_templates: {}
    rate_limit_mode: 
    required_roles:
    - notExistingRole
url_matches:
- backend_prefix: "/v2/"
  frontend_prefix: "/swaggerpetstore/"
```

I also configured a user with role 'user'. I would expect this user to be able to access the API to all request methods and endpoints except POST to the /pet/ endpoint because the 'notExistingRole' is missing.

Instead also POST requests to the /pet/ endpoint are proxied.

How can i restrict POST requests to the /pet/ endpoint? Thanks in advance!
