### ISSUE TITLE
Trafficserver has additional timeout not tied to configuration

### ISSUE THREAD

**Issue by science695** [NREL/api-umbrella#441]
I have been trying to get an api long-running process (more than 15 minutes) to run through umbrella.

I have set all 3 nginx timeouts to 3600 seconds, but it keeps getting a gateway timeout at 900 (15minutes).

I found a setting in trafficserver/records.config:

> CONFIG proxy.config.http.transaction_active_timeout_in INT 900

It seems like this setting shold also be tied to proxy_read_timeout like https://github.com/NREL/api-umbrella/blob/ae8ef4121f9cbe63093d15bb086b1a1c62eb6fba/src/api-umbrella/cli/read_config.lua#L370

Is there any danger of setting this in the api-umbrella.yml config file:
```
trafficserver:
  embedded_server_config:
    records:
      - "CONFIG proxy.config.http.transaction_active_timeout_in INT 3600"
      - "CONFIG proxy.config.http.connect_attempts_timeout INT 3600"
      - "CONFIG proxy.config.http.post_connect_attempts_timeout INT 3600"
```
or setting it to 0 so it doesn't introduce another timeout to the process?

**Comment by science695** [comment]
I found 2 more timeouts in trafficserver (they default to 1800 seconds or 30minutes).

So far I have not had any problems....

**Comment by science695** [comment]
I noticed that there have been alot of improvements since the v0.14.4 release, I believe this problem was fixed in June of 2018.

Is there any new release so that we could more easily use your updates?

**Comment by GUI** [comment]
@science695: Sorry for the delay, but thanks for the heads up! Yes, you're right that this was fixed earlier and is now part of the v0.15.1 release. This should now be configurable via `/etc/api-umbrella/api-umbrella.yml` with the following settings:

```yaml
nginx:
  proxy_connect_timeout: 60
  proxy_read_timeout: 60
  proxy_send_timeout: 60
```

The documentation for these timeout settings can be found for the underlying nginx settings here: http://nginx.org/en/docs/http/ngx_http_proxy_module.html

What's fixed in v0.15.1 is that configuring these nginx settings in API Umbrella should now automatically tune the underlying TrafficServer settings to match.
