### ISSUE TITLE
Latest docker image broken? 

### ISSUE THREAD

**Issue by tjma2001** [NREL/api-umbrella#467]
I am using the latest docker image 0.15.1. I am doing the bare minimum and running it through docker-compose. 

```
version: '3.1'
services:
  api:
    # build: .
    image: nrel/api-umbrella:0.15.1
    volumes:
      - ./config/:/etc/api-umbrella/
      # - ./log/:/var/log/api-umbrella:rw
    ports:
      - "80:80"
      - "443:443"
networks:
  default:
    external:
      name: client_api
```

My api-umbrella.yml file is empty. I run the project and there seems to be no errors. I then execute `curl -vk https://localhost` and I get the following response:

![image](https://user-images.githubusercontent.com/8049309/62747975-20663100-ba57-11e9-8539-5979b5c77468.png)

This issue is not present on 0.14.4. There I can just run the same compose file as above without running into any issues when its run with curl. 

I also booted up a virtualmachine and did the `apt-get` install method for `api-umbrella` and it runs fine. I just can't seem to get it running properly through docker.
