### ISSUE TITLE
Missing alias with data analytics when use aws elasticseach 7.1

### ISSUE THREAD

**Issue by Buminta** [NREL/api-umbrella#476]
I'm using docker version `0.15.1`

With `api-umbrella.yml` file:

```
services:
  - general_db
#  - log_db
  - router
  - web
elasticsearch:
  hosts:
    - "https://vpc-..............es.amazonaws.com"
  index_name_prefix: api-umbrella
  index_partition: monthly
  index_mapping_type: log
  api_version: 7
  template_version: 2
```

However i seen it's only write logs to ES, but can't get logs for analytics in here!

![Screen Shot 2019-08-30 at 4 27 42 PM](https://user-images.githubusercontent.com/5722956/64009995-1e1d6100-cb43-11e9-82d9-56b7f335170a.png)

What's i can do it?
