### ISSUE TITLE
Authenticate API-Umbrella with Oracle Identity Cloud Service (IDCS) via OIDC

### ISSUE THREAD

**Issue by dan-king** [NREL/api-umbrella#508]
How can API-Umbrella connect to Oracle Identify Cloud Service (IDCS) for authentication?
(Oracle IDCS supports the OIDC protocol, as does Facebook, GitHub, CAS, et al.)

Is it as simple as plugging in our Oracle IDCS values into the CAS configuration via the api-umbrella.yml?

I.e.
> **/etc/api-umbrella/api-umbrella.yml**
```
web:
  admin:
    auth_strategies:
      enabled:
        - cas
      cas:
        options:
          host: example.idcs.oracle.com
          login_url: /path/to/oracle/idcs/login
          logout_url: /path/to/oracle/idcs/logout
          client_id: "CLIENT_ID_HERE"
          client_secret: "CLIENT_ID_HERE"
```

Or would a connector simialr to CAS, Facebook, GitHub, etc. need to be written in order to authenticate via an Oracle identity provider?
