### ISSUE TITLE
Password reset instructions not sent

### ISSUE THREAD

**Issue by asokolsky** [NREL/api-umbrella#525]
I can't login as administrator after the installation and password reset instructions are not sent.

centos7 runs postfix which relays e-mail to my gmail account.
api-umbrella installed from pre-compiled binaries.
/etc/api-umbrella/api-umbrella.yml:
```
http_port: 8080
https_port: 8443
services:
  - general_db
  - log_db
  - router
  - web
web:
  admin:
    initial_superusers:
      - asokolsky@gmail.com
    auth_strategies:
      enabled:
        - local
    username_is_email: true
    password_length_min: 1
    password_length_max: 72
  mailer:
    smtp_settings:
      address: localhost
elasticsearch:
  hosts:
    - http://127.0.0.1:14002
mongodb:
  url: mongodb://127.0.0.1:14001/api_umbrella
nginx:
  workers: 2
gatekeeper:
  workers: 2
```
