### ISSUE TITLE
How to configure SMTP?

### ISSUE THREAD

**Issue by brylie** [NREL/api-umbrella#82]
How do we configure SMTP? E.g. we want to specify the SMTP server manually.

**Comment by GUI** [comment]
Oops, sorry this slipped past me.

Inside your `/etc/api-umbrella/api-umbrella.yml` config file, you'll add settings under the `web.mailer.smtp_settings` key. The configuration under this key gets passed directly to Rails's Action Mailer `smtp_settings` configuration, so you can see all the valid configuration options in the [Action Mailer docs](http://guides.rubyonrails.org/action_mailer_basics.html#action-mailer-configuration).

As a quick example, your configuration might look something like:

```yml
web:
  mailer:
    smtp_settings:
      address: smtp.whatever.com
      authentication: login
      user_name: example
      password: super_secure_pass
```

But again, I'd refer to the Action Mailer `smtp_settings` configuration for all the available options. Let me know if you run into any issues with setting this up.
